name: API Tests

on:
  push:
    branches:
      - main
      - dev

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Postman collection with Newman
        run: |
          newman run postman/collections/Practice_API_Testing.postman_collection.json \
          --env-var base_URL=${{ secrets.BASE_URL }} \
          -r cli,htmlextra \
          --reporter-htmlextra-export reports/api-test-report.html

      - name: Upload Newman HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: reports/api-test-report.html