name: API Tests

on:
  push:
    branches: [ "main", "development"]
  pull_request:
    branches: [ "main" ]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Postman collection with Newman
        run: |
          newman run postman/collections/Practice_API_Testing.postman_collection.json \
          --env-var "base_URL=${{ secrets.BASE_URL }}" \
          --env-var "valid_username=${{ secrets.VALID_USERNAME }}" \
          --env-var "valid_password=${{ secrets.VALID_PASSWORD }}" \
          --env-var "invalid_username=wrong_username" \
          --env-var "invalid_password=wrong_password" \
          -r cli,htmlextra \
          --reporter-htmlextra-export reports/api-test-report.html

      - name: Upload Newman HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: reports/api-test-report.html